site_name: WildLife ReID App
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
  #ogo: media/project_top_image.png
  #icon:
  #  repo: material/github
#repo_name: WildLife ReID App
nav:
  - Introduction: index.md
  - User Guide:
    - Getting Started: first_steps.md
    - Taxon classification: taxon_classification.md
    - Identification: identification.md
    - Cloud import: cloud_import.md
  - Technical Documentation:
    - Architecture: architecture.md
    - Installation: install.md
    - Configuration: configuration.md
  - Build the docs: build_docs.md
  - Contact: contact.md

#markdown_extensions:
#  - toc:
#      permalink: true